In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\HP\Documents\house_prices_missing.csv")
df

    size  bedrooms   age  distance   price
0  120.0       3.0  10.0       5.0  220000
1  150.0       4.0   NaN       7.0  260000
2    NaN       2.0  20.0       3.0  180000
3  200.0       NaN   5.0      10.0  320000
4  170.0       3.0   8.0       NaN  280000
5   90.0       2.0  30.0       2.0  150000

In [4]:
df['size']=df['size'].fillna(df['size'].median())

In [14]:
df['size'].astype(int)

0    120
1    150
2    146
3    200
4    170
5     90
Name: size, dtype: int64

In [15]:
df['bedrooms']=df['bedrooms'].fillna(df['bedrooms'].median())

In [16]:
df['bedrooms'].astype(int)

0    3
1    4
2    2
3    2
4    3
5    2
Name: bedrooms, dtype: int64

In [12]:
df['age']=df['age'].fillna(df['age'].median())

In [17]:
df['age'].astype(int)

0    10
1    14
2    20
3     5
4     8
5    30
Name: age, dtype: int64

In [18]:
df['distance']=df['distance'].fillna(df['distance'].median())

In [19]:
df['distance'].astype(int)

0     5
1     7
2     3
3    10
4     5
5     2
Name: distance, dtype: int64

In [23]:
X=df.drop('price',axis="columns")
y=df['price']

In [24]:
X

    size  bedrooms   age  distance
0  120.0       3.0  10.0       5.0
1  150.0       4.0  14.6       7.0
2  146.0       2.0  20.0       3.0
3  200.0       2.8   5.0      10.0
4  170.0       3.0   8.0       5.0
5   90.0       2.0  30.0       2.0

In [25]:
y

0    220000
1    260000
2    180000
3    320000
4    280000
5    150000
Name: price, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [29]:
model.coef_

array([  635.20387565, 14135.96458669, -1898.21126758,  6457.66245989])

In [30]:
model.intercept_

np.float64(95952.55136624345)

In [31]:
y_pred=model.predict(X_test)

In [32]:
mse=mean_squared_error(y_test,y_pred)

In [33]:
y_pred

array([227891.109828  , 265266.74377311])

In [34]:
mse

45004102.14460665

In [39]:
from sklearn.metrics import r2_score

In [40]:
accuracy=r2_score(y_test,y_pred)

In [41]:
accuracy

0.8874897446384834

In [53]:
model.predict([[140,3,15,10]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([263392.44330254])

In [54]:
140*635.20387565+3*14135.96458669+15*-1898.21126758+10*6457.66245989+95952.55136624345

263392.44330251345